import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb, type AppDatabase } from "@/lib/db/client";
import { goalInputSchema, goalStatusSchema } from "@/lib/db/contracts";
import { createGoalRepository } from "@/lib/db/repositories/goal-repository";

const querySchema = z.object({ status: goalStatusSchema.optional(), includeArchived: z.enum(["true", "false"]).default("false").transform((value) => value === "true") }).strict();
export async function GET(request: Request) { return getGoals(request, getDb()); }
export async function getGoals(request: Request, database: AppDatabase) { const requestId = randomUUID(); try { const query = querySchema.parse(Object.fromEntries(new URL(request.url).searchParams)); const goals = await createGoalRepository(database).findAll(query.includeArchived); const filtered = query.status ? goals.filter((goal) => goal.status === query.status) : goals; return NextResponse.json(filtered.sort((a, b) => Number(b.status === "active") - Number(a.status === "active") || Number(a.priority !== "primary") - Number(b.priority !== "primary") || (a.targetDate ?? "9999").localeCompare(b.targetDate ?? "9999") || b.updatedAt.localeCompare(a.updatedAt))); } catch (error) { if (error instanceof z.ZodError) return errorResponse("VALIDATION_ERROR", "Les filtres d’objectifs sont invalides", requestId, 400); return errorResponse("DATABASE_ERROR", "Les objectifs sont indisponibles", requestId, 500); } }
export async function POST(request: Request) { return createGoal(request, getDb()); }
export async function createGoal(request: Request, database: AppDatabase) { const requestId = randomUUID(); try { const input = goalInputSchema.parse(await request.json()); const now = new Date().toISOString(); const goal = await createGoalRepository(database).create({ id: randomUUID(), title: input.title, type: input.type, priority: input.priority, status: input.status, startDate: input.startDate ?? null, targetDate: input.targetDate ?? null, targetValue: input.targetValue ?? null, targetUnit: input.targetUnit ?? null, description: input.description ?? null, definitionJson: JSON.stringify(input.definition), createdAt: now, updatedAt: now }); return NextResponse.json(goal, { status: 201 }); } catch (error) { if (error instanceof z.ZodError) return errorResponse("VALIDATION_ERROR", "Vérifiez les champs de l’objectif", requestId, 400); if (error instanceof Error && error.message.includes("Un seul objectif")) return errorResponse("VALIDATION_ERROR", error.message, requestId, 409); return errorResponse("DATABASE_ERROR", "L’objectif n’a pas pu être enregistré", requestId, 500); } }
function errorResponse(code: string, message: string, requestId: string, status: number) { return NextResponse.json({ error: { code, message, requestId } }, { status }); }