import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import type { activityDetailsCache, activityStreamSummaries, athleteContextVersions, goals, manualSessions, syncedActivities, userConfirmations, activityContexts, analyses, actionItems } from "./schema";

export type SyncedActivity = InferSelectModel<typeof syncedActivities>;
export type NewSyncedActivity = InferInsertModel<typeof syncedActivities>;
export type ManualSession = InferSelectModel<typeof manualSessions>;
export type NewManualSession = InferInsertModel<typeof manualSessions>;
export type Confirmation = InferSelectModel<typeof userConfirmations>;
export type NewConfirmation = InferInsertModel<typeof userConfirmations>;
export type AthleteContextVersion = InferSelectModel<typeof athleteContextVersions>;
export type NewAthleteContextVersion = InferInsertModel<typeof athleteContextVersions>;
export type Goal = InferSelectModel<typeof goals>;
export type NewGoal = InferInsertModel<typeof goals>;
export type ActivityDetailsCache = InferSelectModel<typeof activityDetailsCache>;
export type ActivityStreamSummary = InferSelectModel<typeof activityStreamSummaries>;
export type ActivityContext = InferSelectModel<typeof activityContexts>;
export type NewActivityContext = InferInsertModel<typeof activityContexts>;
export type Analysis = InferSelectModel<typeof analyses>;
export type NewAnalysis = InferInsertModel<typeof analyses>;
export type ActionItem = InferSelectModel<typeof actionItems>;
export type NewActionItem = InferInsertModel<typeof actionItems>;