"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { AthleteContextV1, GoalInput } from "@/lib/db/contracts";
import type { Goal } from "@/lib/db/types";
import { AthleteContextForm, emptyContext } from "./athlete-context-form";
import { GoalForm } from "./goal-form";
import { GoalItem } from "./goal-item";
import { PerformanceProfilePanel } from "./performance-profile-panel";

export function ContextPage() {
  const [context, setContext] = useState<AthleteContextV1>(emptyContext); const [activatedAt, setActivatedAt] = useState<string | null>(null); const [goals, setGoals] = useState<Goal[]>([]); const [loading, setLoading] = useState(true); const [goalForm, setGoalForm] = useState(false); const [editingGoal, setEditingGoal] = useState<Goal>(); const [error, setError] = useState<string>();
  useEffect(() => { void Promise.all([fetch("/api/context").then((response) => response.json() as Promise<{ context?: AthleteContextV1; activatedAt?: string | null } | null>), fetch("/api/goals").then((response) => response.json() as Promise<Goal[]>)]).then(([activeContext, loadedGoals]) => { if (activeContext?.context) { setContext(activeContext.context); setActivatedAt(activeContext.activatedAt ?? null); } setGoals(loadedGoals); }).catch(() => setError("Impossible de charger votre contexte.")).finally(() => setLoading(false)); }, []);
  if (loading) return <main className="shell"><section className="panel state"><span className="spinner" />Chargement de Mon contexte...</section></main>;
  return <main className="shell"><header className="topbar"><Link className="brand" href="/">RUN <span>INSIGHTS</span></Link><Link className="back-link" href="/">Retour au dashboard</Link></header><section className="context-hero"><p className="kicker">Cadre explicite</p><h1>{activatedAt ? "Mon contexte" : "Définissez votre contexte d’entraînement"}</h1><p>Ces informations servent de cadre explicite à vos futures analyses. Elles ne sont pas déduites automatiquement de vos activités.</p></section>{error && <section className="panel state error"><p>{error}</p></section>}<AthleteContextForm initialContext={context} activeDate={activatedAt} onSaved={(saved, date) => { setContext(saved); setActivatedAt(date); }} /><PerformanceProfilePanel /><section className="goals-section"><div className="section-heading"><div><p className="kicker">Objectifs structurés</p><h2>Objectifs</h2></div><button className="button" onClick={() => { setEditingGoal(undefined); setGoalForm(true); }}>Ajouter un objectif</button></div>{goalForm && <GoalForm goalId={editingGoal?.id} initial={editingGoal ? { title: editingGoal.title, type: editingGoal.type as GoalInput["type"], priority: editingGoal.priority as GoalInput["priority"], status: editingGoal.status === "archived" ? "paused" : editingGoal.status as GoalInput["status"], startDate: editingGoal.startDate ?? undefined, targetDate: editingGoal.targetDate ?? undefined, targetValue: editingGoal.targetValue ?? undefined, targetUnit: editingGoal.targetUnit ?? undefined, description: editingGoal.description ?? undefined, definition: JSON.parse(editingGoal.definitionJson) as Record<string, unknown> } : undefined} onSaved={(goal) => { const savedGoal = goal as Goal; setGoals((current) => editingGoal ? current.map((item) => item.id === savedGoal.id ? savedGoal : item) : [savedGoal, ...current]); setGoalForm(false); setEditingGoal(undefined); }} onCancel={() => { setGoalForm(false); setEditingGoal(undefined); }} />}{goals.length === 0 ? <p className="manual-empty">Aucun objectif déclaré.</p> : <div className="goal-list">{goals.map((goal) => <GoalItem key={goal.id} goal={goal} onEdit={() => { setEditingGoal(goal); setGoalForm(true); }} onChange={(changed) => setGoals((current) => current.map((item) => item.id === changed.id ? changed : item))} />)}</div>}</section></main>;
}