"use client";

import { useState } from "react";
import type { GoalInput } from "@/lib/db/contracts";

type Props = { initial?: Partial<GoalInput>; goalId?: string; onSaved: (goal: unknown) => void; onCancel: () => void };
export function GoalForm({ initial, goalId, onSaved, onCancel }: Props) {
  const [value, setValue] = useState<GoalInput>({ title: initial?.title ?? "", type: initial?.type ?? "general", priority: initial?.priority ?? "secondary", status: initial?.status ?? "active", startDate: initial?.startDate, targetDate: initial?.targetDate, targetValue: initial?.targetValue, targetUnit: initial?.targetUnit, description: initial?.description, definition: initial?.definition ?? {} }); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const response = await fetch(goalId ? `/api/goals/${goalId}` : "/api/goals", { method: goalId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const payload: unknown = await response.json(); if (!response.ok) throw new Error((payload as { error?: { message?: string } }).error?.message ?? "L’objectif n’a pas pu être enregistré."); onSaved(payload); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Erreur d’enregistrement."); } finally { setSaving(false); } }
  return <form className="goal-form" onSubmit={submit}><div className="form-grid"><label>Titre<input required maxLength={150} value={value.title} onChange={(event) => setValue({ ...value, title: event.target.value })} /></label><label>Type<select value={value.type} onChange={(event) => setValue({ ...value, type: event.target.value as GoalInput["type"] })}><option value="general">Général</option><option value="race">Course</option><option value="performance">Performance</option><option value="process">Processus</option><option value="technical_observation">Observation technique</option></select></label><label>Priorité<select value={value.priority} onChange={(event) => setValue({ ...value, priority: event.target.value as GoalInput["priority"] })}><option value="secondary">Secondaire</option><option value="primary">Primary</option></select></label><label>Statut<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as GoalInput["status"] })}><option value="active">Actif</option><option value="paused">En pause</option></select></label><label>Échéance<input type="date" value={value.targetDate ?? ""} onChange={(event) => setValue({ ...value, targetDate: event.target.value || undefined })} /></label><label>Valeur cible<input type="number" value={value.targetValue ?? ""} onChange={(event) => setValue({ ...value, targetValue: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Unité<input maxLength={50} placeholder="km, min/km..." value={value.targetUnit ?? ""} onChange={(event) => setValue({ ...value, targetUnit: event.target.value })} /></label><label className="wide">Description<textarea maxLength={1000} rows={2} value={value.description ?? ""} onChange={(event) => setValue({ ...value, description: event.target.value })} /></label></div>{value.priority === "primary" && value.status === "active" && <p className="goal-warning">Cet objectif remplacera la priorité principale active existante.</p>}{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="quiet-button" onClick={onCancel}>Annuler</button><button className="button" disabled={saving}>{saving ? "Enregistrement..." : goalId ? "Enregistrer" : "Créer l’objectif"}</button></div></form>;
}