"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, Timer } from "lucide-react";
import Link from "next/link";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { NormalizedStreams } from "@/lib/db/contracts";
import type { Activity, Lap } from "@/lib/intervals/schemas";
import { formatDate, formatDistance, formatDuration, formatPace } from "@/lib/formatters";
import { segmentActivity, type SegmentationStrategy } from "@/lib/analysis/segmentation";

type Detail = { activity: Activity; intervals: Lap[]; dataAvailability: { intervals: boolean }; sourceMetadata: { cacheStatus: string; fetchedAt: string; sourceUpdatedAt: string | null } };
type Tab = "summary" | "intervals" | "charts";

export function ActivityDetail({ id }: { id: string }) {
  const [detail, setDetail] = useState<Detail>(); const [streams, setStreams] = useState<NormalizedStreams>(); const [tab, setTab] = useState<Tab>("summary"); const [strategy, setStrategy] = useState<SegmentationStrategy>("lap"); const [error, setError] = useState<string>(); const [streamError, setStreamError] = useState<string>();
  useEffect(() => { fetch(`/api/activities/${encodeURIComponent(id)}`).then(async (response) => { const payload: unknown = await response.json(); if (!response.ok) throw new Error((payload as { error?: { message?: string } }).error?.message ?? "Erreur de chargement"); return payload as Detail; }).then(setDetail).catch((loadError: unknown) => setError(loadError instanceof Error ? loadError.message : "Erreur de chargement")); }, [id]);
  useEffect(() => { if (tab !== "charts" || streams) return; fetch(`/api/activities/${encodeURIComponent(id)}/streams`).then(async (response) => { const payload: unknown = await response.json(); if (!response.ok) throw new Error("Les courbes ne sont pas disponibles."); return payload as NormalizedStreams; }).then(setStreams).catch((loadError: unknown) => setStreamError(loadError instanceof Error ? loadError.message : "Les courbes ne sont pas disponibles.")); }, [id, tab, streams]);
  if (error) return <main className="shell"><Link className="back-link" href="/"><ArrowLeft size={16} /> Toutes les activités</Link><section className="panel state error"><strong>Cette activité ne peut pas être chargée.</strong><p>{error}</p></section></main>;
  if (!detail) return <main className="shell"><Link className="back-link" href="/"><ArrowLeft size={16} /> Toutes les activités</Link><section className="panel state"><span className="spinner" />Chargement de la séance...</section></main>;
  const { activity, intervals } = detail; const segmented = segmentActivity({ laps: intervals, streams }, strategy);
  return <main className="shell"><Link className="back-link" href="/"><ArrowLeft size={16} /> Toutes les activités</Link><section className="detail-head"><div><p className="kicker">{formatDate(activity.start_date_local ?? activity.start_date)} · {activity.type}</p><h1>{activity.name}</h1></div><span className="detail-mark"><Timer size={19} /> {detail.sourceMetadata.cacheStatus === "fresh" ? "Cache récent" : "Données source"}</span></section><div className="summary-grid"><Summary label="Distance" value={formatDistance(activity.distance)} /><Summary label="Durée" value={formatDuration(activity.moving_time ?? activity.elapsed_time)} /><Summary label="Allure moyenne" value={formatPace(activity.average_speed)} /><Summary label="FC moyenne" value={activity.average_heartrate ? `${Math.round(activity.average_heartrate)} bpm` : "—"} /></div><nav className="detail-tabs" aria-label="Détail de l’activité">{([["summary", "Résumé"], ["intervals", "Intervalles"], ["charts", "Courbes"]] as const).map(([key, label]) => <button className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key)}>{label}</button>)}</nav>{tab === "summary" && <section className="panel laps-panel"><p className="kicker">Données disponibles</p><h2>Résumé de la séance</h2><p className="data-note">Métadonnées et intervalles chargés depuis Intervals.icu. Aucune interprétation automatique.</p></section>}{tab === "intervals" && <section className="panel laps-panel"><div className="section-heading"><div><p className="kicker">Découpage descriptif</p><h2>Intervalles</h2></div><select value={strategy} onChange={(event) => setStrategy(event.target.value as SegmentationStrategy)}><option value="lap">Laps</option><option value="thirds">Tiers</option><option value="adaptive">Adaptatif</option></select></div>{segmented.segments.length === 0 ? <div className="empty-row">Aucun intervalle disponible.</div> : <div className="table-wrap"><table><thead><tr><th>Segment</th><th>Temps</th><th>Distance</th><th>Allure</th><th>FC moy.</th><th>Cadence</th></tr></thead><tbody>{segmented.segments.map((segment) => <tr key={`${segment.lapId}-${segment.index}`}><th>{segment.lapId} · {segment.index + 1}</th><td>{formatDuration(segment.durationS)}</td><td>{formatDistance(segment.distanceM)}</td><td>{formatPace(segment.averageSpeedMps)}</td><td>{segment.averageHeartRateBpm ? `${Math.round(segment.averageHeartRateBpm)} bpm` : "—"}</td><td>{segment.averageCadenceSpm ? `${Math.round(segment.averageCadenceSpm)} pas/min` : "—"}</td></tr>)}</tbody></table></div>}</section>}{tab === "charts" && <StreamsPanel streams={streams} error={streamError} />}</main>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="summary-item"><small>{label}</small><strong>{value}</strong></div>; }
function StreamsPanel({ streams, error }: { streams?: NormalizedStreams; error?: string }) { if (error) return <section className="panel state error"><BarChart3 size={20} /><strong>{error}</strong><p>Les séries restent facultatives et ne sont pas persistées.</p></section>; if (!streams) return <section className="panel state"><span className="spinner" />Chargement des courbes...</section>; const series = [{ key: "speedMps", label: "Vitesse", unit: "m/s", color: "#f0785f" }, { key: "heartRateBpm", label: "Fréquence cardiaque", unit: "bpm", color: "#5d86a6" }, { key: "cadenceSpm", label: "Cadence", unit: "pas/min", color: "#7c9250" }, { key: "altitudeM", label: "Altitude", unit: "m", color: "#8b6b52" }, { key: "powerW", label: "Puissance", unit: "W", color: "#956ca8" }] as const; const points = streams.elapsedTimeS.map((time, index) => ({ time, ...Object.fromEntries(series.map(({ key }) => [key, streams[key]?.[index] ?? null])) })); return <section className="charts-panel">{series.filter(({ key }) => streams.availability[key === "speedMps" ? "speed" : key === "heartRateBpm" ? "heartRate" : key === "cadenceSpm" ? "cadence" : key === "altitudeM" ? "altitude" : "power"]).map(({ key, label, unit, color }) => <div className="stream-chart" key={key}><div className="section-heading"><h2>{label}</h2><span>{unit}</span></div><ResponsiveContainer width="100%" height={190}><LineChart data={points}><XAxis dataKey="time" tickFormatter={(value) => `${Math.round(value)}s`} /><YAxis unit={` ${unit}`} width={58} /><Tooltip labelFormatter={(value) => `${value}s`} formatter={(value: unknown) => [typeof value === "number" ? value.toFixed(1) : "—", unit]} /><Line type="monotone" dataKey={key} stroke={color} dot={false} connectNulls={false} /></LineChart></ResponsiveContainer></div>)}{!Object.values(streams.availability).some(Boolean) && <p className="data-note">Aucune série graphique disponible.</p>}</section>; }
